/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StaffService } from "../staff.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StaffCreateInput } from "./StaffCreateInput";
import { Staff } from "./Staff";
import { StaffFindManyArgs } from "./StaffFindManyArgs";
import { StaffWhereUniqueInput } from "./StaffWhereUniqueInput";
import { StaffUpdateInput } from "./StaffUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StaffControllerBase {
  constructor(
    protected readonly service: StaffService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Staff })
  @nestAccessControl.UseRoles({
    resource: "Staff",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStaff(@common.Body() data: StaffCreateInput): Promise<Staff> {
    return await this.service.createStaff({
      data: {
        ...data,

        hostel: data.hostel
          ? {
              connect: data.hostel,
            }
          : undefined,
      },
      select: {
        address: true,
        contactInformation: true,
        createdAt: true,

        hostel: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        photo: true,
        position: true,
        qualification: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Staff] })
  @ApiNestedQuery(StaffFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Staff",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async staffItems(@common.Req() request: Request): Promise<Staff[]> {
    const args = plainToClass(StaffFindManyArgs, request.query);
    return this.service.staffItems({
      ...args,
      select: {
        address: true,
        contactInformation: true,
        createdAt: true,

        hostel: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        photo: true,
        position: true,
        qualification: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Staff })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Staff",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async staff(
    @common.Param() params: StaffWhereUniqueInput
  ): Promise<Staff | null> {
    const result = await this.service.staff({
      where: params,
      select: {
        address: true,
        contactInformation: true,
        createdAt: true,

        hostel: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        photo: true,
        position: true,
        qualification: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Staff })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Staff",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStaff(
    @common.Param() params: StaffWhereUniqueInput,
    @common.Body() data: StaffUpdateInput
  ): Promise<Staff | null> {
    try {
      return await this.service.updateStaff({
        where: params,
        data: {
          ...data,

          hostel: data.hostel
            ? {
                connect: data.hostel,
              }
            : undefined,
        },
        select: {
          address: true,
          contactInformation: true,
          createdAt: true,

          hostel: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          photo: true,
          position: true,
          qualification: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Staff })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Staff",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStaff(
    @common.Param() params: StaffWhereUniqueInput
  ): Promise<Staff | null> {
    try {
      return await this.service.deleteStaff({
        where: params,
        select: {
          address: true,
          contactInformation: true,
          createdAt: true,

          hostel: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          photo: true,
          position: true,
          qualification: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
